import {useEffect,useMemo,useRef} from 'react';
import {Canvas,useThree,useFrame} from '@react-three/fiber';
import * as THREE from 'three';
import {experience,seeded} from '../../experience/timeline';
const vertex=`attribute vec3 target;attribute float luminance;attribute float delay;uniform float progress;uniform float scaleFactor;uniform vec2 pointer;varying float alpha;varying float shade;
void main(){float turn=smoothstep(.12,.43,progress)*.72;float d=smoothstep(.26+delay*.14,.82+delay*.09,progress);vec3 p=position;float c=cos(turn),s=sin(turn);p=vec3(p.x*c+p.z*s,p.y,-p.x*s+p.z*c);p+=vec3(pointer.x,pointer.y,0.)*.025*(1.-d);vec3 flow=target;flow.y+=sin(position.y*2.5+d*3.14)*d*.4;p=mix(p,flow,d);p*=scaleFactor;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=(2.1+luminance*1.7)*(1.+d*.6);alpha=(1.-smoothstep(.72,.98,progress))*(.65+luminance*.35);shade=luminance;}`;
const fragment=`varying float alpha;varying float shade;void main(){float r=length(gl_PointCoord-.5);if(r>.5)discard;gl_FragColor=vec4(mix(vec3(.72,.65,.53),vec3(.98,.95,.88),shade),alpha*(1.-smoothstep(.28,.5,r)));}`;
function Cloud({onReady,onError}:{onReady:()=>void;onError:()=>void}){const {invalidate,size,gl}=useThree();const geometry=useMemo(()=>new THREE.BufferGeometry(),[]);const material=useMemo(()=>new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,uniforms:{progress:{value:0},scaleFactor:{value:1},pointer:{value:new THREE.Vector2()}}}),[]);const loaded=useRef(false);
useEffect(()=>{let live=true;const image=new Image();image.onload=()=>{if(!live)return;try{const canvas=document.createElement('canvas');canvas.width=canvas.height=650;const ctx=canvas.getContext('2d')!;ctx.drawImage(image,0,0,650,650);const pixels=ctx.getImageData(0,0,650,650).data;const pos:number[]=[],targets:number[]=[],lum:number[]=[],delays:number[]=[];const step=innerWidth<600?3:2;let n=0;for(let y=30;y<630;y+=step)for(let x=35;x<615;x+=step){const l=pixels[(y*650+x)*4]/255;if(l<.25||seeded(x+y*650)>.25+l*.75)continue;const px=(x/650-.5)*5.6,py=(.5-y/650)*5.6;const oval=Math.max(0,1-(px/2)**2-(py/2.6)**2);const z=Math.sqrt(oval)*.65+Math.exp(-px*px*15-(py+.1)**2*3)*.25;pos.push(px,py,z);targets.push(px-3-seeded(n+11)*8,py+(seeded(n+37)-.5)*8,(seeded(n+19)-.5)*5);lum.push(l);delays.push(seeded(n++));}geometry.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geometry.setAttribute('target',new THREE.Float32BufferAttribute(targets,3));geometry.setAttribute('luminance',new THREE.Float32BufferAttribute(lum,1));geometry.setAttribute('delay',new THREE.Float32BufferAttribute(delays,1));loaded.current=true;onReady();invalidate()}catch{onError()}};image.onerror=onError;image.src='/assets/hero/portrait-fallback.webp';return()=>{live=false;geometry.dispose();material.dispose()}},[]);
useEffect(()=>{experience.invalidate=invalidate;const lost=(e:Event)=>{e.preventDefault();onError()};gl.domElement.addEventListener('webglcontextlost',lost);return()=>{experience.invalidate=()=>{};gl.domElement.removeEventListener('webglcontextlost',lost)}},[invalidate,gl]);
useEffect(()=>{if(matchMedia('(pointer:coarse)').matches)return;const move=(e:PointerEvent)=>{if(experience.progress>.98)return;material.uniforms.pointer.value.set(e.clientX/innerWidth-.5,.5-e.clientY/innerHeight);invalidate()};window.addEventListener('pointermove',move,{passive:true});return()=>window.removeEventListener('pointermove',move)},[invalidate,material]);
useFrame(()=>{material.uniforms.progress.value=experience.progress;material.uniforms.scaleFactor.value=size.width<600?.62:size.width<900?.82:1;});return <points geometry={geometry} material={material} frustumCulled={false}/>}
export default function Particles(props:{onReady:()=>void;onError:()=>void}){return <Canvas camera={{position:[0,0,8],fov:40}} dpr={Math.min(devicePixelRatio,1.5)} frameloop="demand" gl={{alpha:true,antialias:false,powerPreference:'low-power'}} aria-hidden="true"><Cloud {...props}/></Canvas>}
